[unstable]
build-std = ["core"]
build-std-features = ["panic_immediate_abort"]

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace nRF82832_xxAA with your chip as listed in `probe-rs-cli chip list`
#runner = "probe-rs-cli run --no-location --chip nRF52832_xxAA"
runner = "probe-run --chip nRF52832_xxAA"
rustflags = [
#  "-Z", "features=host_dep",
  # Code-size optimizations.
#   "-Z", "trap-unreachable=no",
  "-C", "inline-threshold=5", # try different values here
  "-C", "no-vectorize-loops", # try with and without this
]

[build]
target = "thumbv7em-none-eabi"

[env]
DEFMT_LOG = "info"
